/*DROP DATABASE IF EXISTS NEWSLETTER;*/
CREATE DATABASE NEWSLETTER;
USE NEWSLETTER;

CREATE TABLE Users (
ID_USER INT PRIMARY KEY NOT NULL,
USERNAME VARCHAR (50),
EMAIL VARCHAR (100) NOT NULL,
PASSWORD VARCHAR (50)
)

CREATE TABLE Articles (
ID_ARTICLE INT PRIMARY KEY NOT NULL,
TITLE VARCHAR (50) NOT NULL,
DESCRIPTION VARCHAR (100),
DATE VARCHAR (50),
CONTENT VARCHAR (100)  NOT NULL
)

CREATE TABLE UserArticle  (
ID_USERATICLE INT PRIMARY KEY NOT NULL,
ID_USER INT,
ID_ARTICLE INT,
READBOLL BIT,
FAVORITE BIT,
READLAST BIT,
CONSTRAINT fk_RelationUser FOREIGN KEY (ID_USER) REFERENCES Users (ID_USER),
CONSTRAINT fk_RelationArticle FOREIGN KEY (ID_ARTICLE) REFERENCES Articles (ID_ARTICLE)
)